version: "3"

services:
  postgres:
    image: postgres:12
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: management
      POSTGRES_PASSWORD: management
      POSTGRES_DB: management
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
